version: 2

models:
  - name: stg_cars
    columns:
      - name: car_id
        tests:
          - unique
          - not_null
      - name: creation_date
      - name: title
      - name: url
      - name: km
      - name: year
      - name: cubic_capacity
      - name: main_province
      - name: fuel_type
      - name: is_financed
      - name: is_certified
      - name: is_professional
      - name: published_date
      - name: price
      - name: financed_price
      - name: price_has_taxes
      - name: warranty_months
      - name: offer_type
      - name: has_stock
      - name: environmental_label
  
  - name: stg_motorcycles
    columns:
      - name: motorcycle_id
        tests:
          - unique
          - not_null
      - name: creation_date
      - name: title
      - name: url
      - name: km
      - name: year
      - name: cubic_capacity
      - name: main_province
      - name: fuel_type
      - name: is_financed
      - name: is_certified
      - name: is_professional
      - name: published_date
      - name: price
      - name: warranty
      - name: offer_type

  - name: stg_cars_snapshots
    columns:
      - name: scd_id
        tests:
          - unique
          - not_null
      - name: car_id
        tests:
          - unique:
              config:
                where: "is_current_version"
          - not_null
      - name: creation_date
      - name: title
      - name: url
      - name: km
      - name: year
      - name: cubic_capacity
      - name: main_province
      - name: fuel_type
      - name: is_financed
      - name: is_certified
      - name: is_professional
      - name: published_date
      - name: price
      - name: financed_price
      - name: price_has_taxes
      - name: warranty_months
      - name: offer_type
      - name: has_stock
      - name: updated_at
      - name: is_current_version
      - name: version
      - name: valid_from
      - name: valid_to
        

  - name: stg_motorcycles_snapshots
    columns:
      - name: scd_id
        tests:
          - unique
          - not_null
      - name: motorcycle_id
        tests:
          - unique:
              config:
                where: "is_current_version"
          - not_null
      - name: creation_date
      - name: title
      - name: url
      - name: km
      - name: year
      - name: cubic_capacity
      - name: main_province
      - name: fuel_type
      - name: is_financed
      - name: is_certified
      - name: is_professional
      - name: published_date
      - name: price
      - name: warranty
      - name: offer_type
      - name: updated_at
      - name: is_current_version
      - name: version
      - name: valid_from
      - name: valid_to

  - name: fct_car_prices
    columns:
      - name: car_id
      - name: date_key
      - name: price
    tests:
      - unique:
          column_name: "(date_key || '-' || car_id)"
          config:
            where: date_key >= current_date - 3
