config:
  send_anonymous_usage_stats: false

default:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: analytics
      path: ../orchestration/data/coches.net.duckdb
      threads: 1
